input {
  beats {
    port => 5044
  }
}

filter {
  if [event][code] == 4625 {
    mutate {
      add_tag => ["failed_login"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "security-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
